export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
